#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-fpc
Version  : 2.2.7
Release  : 39
URL      : https://cran.r-project.org/src/contrib/fpc_2.2-7.tar.gz
Source0  : https://cran.r-project.org/src/contrib/fpc_2.2-7.tar.gz
Summary  : Flexible Procedures for Clustering
Group    : Development/Tools
License  : GPL-2.0
Requires: R-diptest
Requires: R-flexmix
Requires: R-kernlab
Requires: R-mclust
Requires: R-prabclus
Requires: R-robustbase
BuildRequires : R-diptest
BuildRequires : R-flexmix
BuildRequires : R-kernlab
BuildRequires : R-mclust
BuildRequires : R-prabclus
BuildRequires : R-robustbase
BuildRequires : buildreq-R

%description
Fixed point clustering. Linear regression clustering. Clustering by 
  merging Gaussian mixture components. Symmetric 
  and asymmetric discriminant projections for visualisation of the 
  separation of groupings. Cluster validation statistics
  for distance based clustering including corrected Rand index. 
  Standardisation of cluster validation statistics by random clusterings and 
  comparison between many clustering methods and numbers of clusters based on
  this.  
  Cluster-wise cluster stability assessment. Methods for estimation of

%prep
%setup -q -c -n fpc
cd %{_builddir}/fpc

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1593189439

%install
export SOURCE_DATE_EPOCH=1593189439
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library fpc
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library fpc
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library fpc
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc fpc || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/fpc/DESCRIPTION
/usr/lib64/R/library/fpc/INDEX
/usr/lib64/R/library/fpc/Meta/Rd.rds
/usr/lib64/R/library/fpc/Meta/data.rds
/usr/lib64/R/library/fpc/Meta/features.rds
/usr/lib64/R/library/fpc/Meta/hsearch.rds
/usr/lib64/R/library/fpc/Meta/links.rds
/usr/lib64/R/library/fpc/Meta/nsInfo.rds
/usr/lib64/R/library/fpc/Meta/package.rds
/usr/lib64/R/library/fpc/NAMESPACE
/usr/lib64/R/library/fpc/R/fpc
/usr/lib64/R/library/fpc/R/fpc.rdb
/usr/lib64/R/library/fpc/R/fpc.rdx
/usr/lib64/R/library/fpc/data/tonedata.txt.gz
/usr/lib64/R/library/fpc/help/AnIndex
/usr/lib64/R/library/fpc/help/aliases.rds
/usr/lib64/R/library/fpc/help/fpc.rdb
/usr/lib64/R/library/fpc/help/fpc.rdx
/usr/lib64/R/library/fpc/help/paths.rds
/usr/lib64/R/library/fpc/html/00Index.html
/usr/lib64/R/library/fpc/html/R.css
/usr/lib64/R/library/fpc/tests/Examples/fpc-Ex.Rout.save
/usr/lib64/R/library/fpc/tests/fpctests_notallin.R
/usr/lib64/R/library/fpc/tests/fpctests_notallin.Rout.save
